# ccage — Claude Code per-project isolation wrapper
#
# Gives each working directory its own CLAUDE_CONFIG_DIR so multiple parallel
# Claude Code sessions (different repos or git worktrees) stop bashing each
# other's prompt cache, credentials, and history.
#
# Works in bash and zsh. Safe to source multiple times.
#
# Opt-outs (set before invoking `claude`):
#   CCAGE_DISABLE=1              — bypass the wrapper entirely for one call
#   CCAGE_KEEP_ATTRIBUTION=1     — don't touch CLAUDE_CODE_ATTRIBUTION_HEADER
#   CCAGE_KEEP_AUTOUPDATER=1     — don't touch DISABLE_AUTOUPDATER
#   CCAGE_NO_AUTO_SIGNORE=1      — don't create a baseline .claudesignore
#   CCAGE_NO_ONBOARDING_PATCH=1  — don't pre-set hasCompletedOnboarding
#
# Config:
#   CCAGE_ROOT                   — parent dir for isolated configs (default: $HOME)
#   CCAGE_PREFIX                 — dir name prefix (default: .claude-)
#
# Extension hooks (redefine in a companion file — see Extension model below):
#   _ccage_config_dir_override PWD
#       Echo a config dir and return 0 to override ccage's default choice.
#       Return non-zero to fall through to the default.
#   _ccage_pre_exec_hook PWD CONFIG_DIR
#       Runs just before `command claude`. Can export env vars, append to the
#       _ccage_extra_args array to inject CLI flags, and write UI-only keys
#       into $CLAUDE_CONFIG_DIR/settings.json (never permissions, plugins, or
#       other state — those cause cross-session cache-bashing).
#
# Extension model:
#   Drop a companion file next to this one that redefines either hook. If you
#   use the default ~/.bashrc.d/ loader, alphabetical order means a file named
#   `claude-overrides.sh` loads after `claude-isolation.sh` and can safely
#   redefine the stubs. An example template ships as claude-overrides.sh.example.

# ---- portable sha1 (sha1sum on Linux, shasum on macOS) ----
_ccage_sha1() {
    if command -v sha1sum >/dev/null 2>&1; then
        printf '%s' "$1" | sha1sum | cut -c1-8
    elif command -v shasum >/dev/null 2>&1; then
        printf '%s' "$1" | shasum -a 1 | cut -c1-8
    else
        printf '%s' "$1" | openssl dgst -sha1 | awk '{print $NF}' | cut -c1-8
    fi
}

# ---- extension hook stubs (no-ops; redefine in a companion file) ----
_ccage_config_dir_override() { return 1; }
_ccage_pre_exec_hook() { :; }

# ---- compute the config dir for a given absolute path ----
_ccage_config_dir_for() {
    local pwd_arg="$1"
    local override
    if override="$(_ccage_config_dir_override "$pwd_arg")" && [ -n "$override" ]; then
        printf '%s\n' "$override"
        return 0
    fi

    local root="${CCAGE_ROOT:-$HOME}"
    local prefix="${CCAGE_PREFIX:-.claude-}"
    local base
    base="$(basename "$pwd_arg")"

    local candidate="$root/${prefix}${base}"
    local marker="$candidate/.owning_path"

    # Collision: dir exists, is owned by a different PWD → disambiguate with hash.
    if [ -d "$candidate" ] && [ -f "$marker" ]; then
        local owner
        owner="$(cat "$marker" 2>/dev/null)"
        if [ -n "$owner" ] && [ "$owner" != "$pwd_arg" ]; then
            local hash
            hash="$(_ccage_sha1 "$pwd_arg")"
            candidate="$root/${prefix}${base}-${hash}"
        fi
    fi
    printf '%s\n' "$candidate"
}

# ---- one-shot claim + bootstrap for a config dir ----
_ccage_bootstrap_dir() {
    local dir="$1"
    local pwd_arg="$2"

    [ -d "$dir" ] || mkdir -p "$dir"
    if [ ! -f "$dir/.owning_path" ]; then
        printf '%s\n' "$pwd_arg" > "$dir/.owning_path"
    fi

    # Pre-set hasCompletedOnboarding so a fresh config dir doesn't drop the user
    # into the login flow when they already have valid credentials elsewhere.
    [ -n "$CCAGE_NO_ONBOARDING_PATCH" ] && return 0

    local cj="$dir/.claude.json"
    if [ ! -f "$cj" ]; then
        printf '%s\n' '{"hasCompletedOnboarding":true}' > "$cj" 2>/dev/null
        return 0
    fi
    if ! grep -q '"hasCompletedOnboarding"' "$cj" 2>/dev/null; then
        if command -v python3 >/dev/null 2>&1; then
            python3 - "$cj" <<'PY' 2>/dev/null
import json, sys
p = sys.argv[1]
try:
    with open(p) as f: d = json.load(f)
except Exception:
    d = {}
d["hasCompletedOnboarding"] = True
with open(p, "w") as f: json.dump(d, f, indent=2)
PY
        fi
    fi
}

# ---- baseline .claudesignore (only if the repo has none) ----
_ccage_write_signore() {
    [ -n "$CCAGE_NO_AUTO_SIGNORE" ] && return 0
    [ -f .claudesignore ] && return 0
    cat > .claudesignore <<'SIGNORE'
# Auto-generated by ccage. Edit freely — ccage won't overwrite this file.
node_modules/
.venv/
venv/
__pycache__/
dist/
build/
*.tar.gz
*.zip
*.sqlite
*.db
.pytest_cache/
.mypy_cache/
.ruff_cache/
.cursor/
.windsurf/
SIGNORE
}

# ---- the wrapper ----
claude() {
    if [ -n "$CCAGE_DISABLE" ]; then
        command claude "$@"
        return
    fi

    export CLAUDE_CONFIG_DIR="$(_ccage_config_dir_for "$PWD")"
    _ccage_bootstrap_dir "$CLAUDE_CONFIG_DIR" "$PWD"
    _ccage_write_signore

    # Suppress the per-request billing header whose rotating `cch=<hash>`
    # destabilizes prompt-cache keys. Mechanism confirmed as of Claude Code
    # v2.1.104 (April 2026). See README for references.
    if [ -z "$CCAGE_KEEP_ATTRIBUTION" ]; then
        export CLAUDE_CODE_ATTRIBUTION_HEADER=0
    fi

    # Parallel sessions racing on a self-update can corrupt the install.
    if [ -z "$CCAGE_KEEP_AUTOUPDATER" ]; then
        export DISABLE_AUTOUPDATER=1
    fi

    # Extension point: overrides can export env, append to _ccage_extra_args,
    # or seed UI-only settings into CLAUDE_CONFIG_DIR. Keep it UI-only —
    # copying state/permissions from a master dir re-creates the cross-session
    # cache-bashing that ccage exists to prevent.
    _ccage_extra_args=()
    _ccage_pre_exec_hook "$PWD" "$CLAUDE_CONFIG_DIR"

    command claude "${_ccage_extra_args[@]}" "$@"
}
